server:
  port: 9000

spring:
  application:
    name: zuul-serser


info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

#eureka 注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    #ip-address: 127.0.0.1 以IP的形式注入实例
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true