spring:
  cloud:
    config:
      #配置git远程仓库
      server:
        git:
          uri: https://gitlab.com/satan_smile/spring-cloud-config.git
          search-paths: resources
          username:
          password:
      label: dev
      allow-override: true
      profile: dev
  #拉取配置文件：host:port/config_name/profiles/label  (如：localhost:8282/gateway/dev/dev)
  rabbitmq:
    host: 192.168.124.133
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 2
        max-concurrency: 2
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
